# frontend-service.yml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # deploymentのfrontendを指定
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
