# tasks-service.yml
apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks # deploymentのtasksを指定
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
