# users-service.yml
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # deploymentのusersを指定
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
